In [1]:
import os
os.environ['USE_PYGEOS'] = '0'
import geopandas as gpd
import pandas as pd

## polygons

In [14]:
es10 = gpd.read_file('./material/eg.es_agg_10km.gpkg')
de10 = gpd.read_file('./material/eg.de_agg_10km.gpkg')
es50 = gpd.read_file('./material/eg.es_agg_50km.gpkg')
de50 = gpd.read_file('./material/eg.de_agg_50km.gpkg')
es150 = gpd.read_file('./material/eg.es_agg_150km.gpkg')
de150 = gpd.read_file('./material/eg.de_agg_150km.gpkg')

es10['nuts0'] = 'ES'
de10['nuts0'] = 'DE'
es50['nuts0'] = 'ES'
de50['nuts0'] = 'DE'
es150['nuts0'] = 'ES'
de150['nuts0'] = 'DE'

es10['extent'] = 10
de10['extent'] = 10
es50['extent'] = 50
de50['extent'] = 50
es150['extent'] = 150
de150['extent'] = 150

poly10 = pd.concat([es10,de10]).reset_index(drop=True)
poly10 = poly10.drop(columns=['left','top','right','bottom'])
poly10['id'] = poly10.index
poly10.to_file('./material/polygon_agg_10km.gpkg')
poly50 = pd.concat([es50,de50]).reset_index(drop=True)
poly50 = poly50.drop(columns=['left','top','right','bottom'])
poly50['id'] = poly50.index
poly50.to_file('./material/polygon_agg_50km.gpkg')
poly150 = pd.concat([es150,de150]).reset_index(drop=True)
poly150 = poly150.drop(columns=['left','top','right','bottom'])
poly150['id'] = poly150.index
poly150.to_file('./material/polygon_agg_150km.gpkg')

# pnt = pnt.to_crs("EPSG:4326")

## real samples falling in this region

In [3]:
es = gpd.read_file('./material/eg_agg_10km_es.gpkg')
de = gpd.read_file('./material/eg_agg_10km_de.gpkg')

es['id'] = es.index
de['id'] = de.index
es['nuts0'] = 'ES'
de['nuts0'] = 'DE'

ag = pd.concat([es, de])
# ag.to_crs("EPSG:4326")

ERROR 1: PROJ: proj_create_from_database: Open of /opt/conda/share/proj failed

In [5]:
# joint with sampled data
from shapely.geometry import Point
df = pd.read_parquet('./material/soc.topsoil_organized.pq')
geometry = [Point(xy) for xy in zip(df['lon'], df['lat'])]
df = gpd.GeoDataFrame(df, geometry=geometry, crs="EPSG:4326")
df = df.to_crs(ag.crs)

In [12]:
ag['polygon_id'] = ag['nuts0'].astype(str) + '-' + ag['id'].astype(str)
sdf = gpd.sjoin(df, ag, how="inner", predicate="within")

In [13]:
sdf

,time,lat,lon,id_left,clay,lc_survey,ref,nuts0_left,ph.h2o,total.n,...,tile_id,geometry,index_right,id_right,left,top,right,bottom,nuts0_right,polygon_id
1178,2002,40.062088,-3.588864,28310,25.000000,cropland,ParcelasINES,ES,NaN,NaN,...,674.0,POINT (3162602.799 1989348.453),1,1,3160000.0,1991000.0,3170000.0,1981000.0,ES,ES-1
1179,2002,40.062404,-3.528971,28311,30.000000,cropland,ParcelasINES,ES,NaN,NaN,...,674.0,POINT (3167652.720 1988469.319),1,1,3160000.0,1991000.0,3170000.0,1981000.0,ES,ES-1
1183,2002,40.016850,-3.587184,28318,30.000000,grassland,ParcelasINES,ES,NaN,NaN,...,674.0,POINT (3161928.826 1984382.140),1,1,3160000.0,1991000.0,3170000.0,1981000.0,ES,ES-1
1719,2002,40.017132,-3.528596,45130,30.700000,cropland,ParcelasINES,ES,NaN,NaN,...,674.0,POINT (3166871.686 1983518.805),1,1,3160000.0,1991000.0,3170000.0,1981000.0,ES,ES-1
34548,2009,40.076570,-3.527850,31681990,2.000000,grassland,LUCAS,ES,7.560000,0.800000,...,674.0,POINT (3168001.446 1989999.595),1,1,3160000.0,1991000.0,3170000.0,1981000.0,ES,ES-1
34565,2009,40.055570,-3.547140,31661988,27.000000,cropland,LUCAS,ES,8.200000,1.100000,...,674.0,POINT (3165999.539 1987999.649),1,1,3160000.0,1991000.0,3170000.0,1981000.0,ES,ES-1
46524,2015,40.055570,-3.547150,31661988,NaN,cropland,LUCAS,ES,8.170000,1.100000,...,674.0,POINT (3165998.696 1987999.801),1,1,3160000.0,1991000.0,3170000.0,1981000.0,ES,ES-1
46543,2015,40.076570,-3.527880,31681990,NaN,grassland,LUCAS,ES,7.620000,1.100000,...,674.0,POINT (3167998.919 1990000.052),1,1,3160000.0,1991000.0,3170000.0,1981000.0,ES,ES-1
75074,2018,40.055490,-3.546811,31661988,NaN,cropland,LUCAS,ES,8.120000,1.100000,...,674.0,POINT (3166025.813 1987985.896),1,1,3160000.0,1991000.0,3170000.0,1981000.0,ES,ES-1
75075,2018,40.076589,-3.527883,31681990,NaN,cropland,LUCAS,ES,7.610000,1.200000,...,674.0,POINT (3167999.008 1990002.173),1,1,3160000.0,1991000.0,3170000.0,1981000.0,ES,ES-1
12841,2008,39.761900,-3.144200,3973,18.000000,cropland,gemas,ES,NaN,NaN,...,674.0,POINT (3194844.963 1949855.493),2,2,3190000.0,1951000.0,3200000.0,1941000.0,ES,ES-2
14781,2008,39.762800,-3.143900,902,53.000000,grassland,gemas,ES,NaN,NaN,...,674.0,POINT (3194886.016 1949949.383),2,2,3190000.0,1951000.0,3200000.0,1941000.0,ES,ES-2
67180,2016,39.747900,-3.176370,45345,27.030000,cropland,ParcelasINES,ES,NaN,NaN,...,674.0,POINT (3191876.126 1948803.861),2,2,3190000.0,1951000.0,3200000.0,1941000.0,ES,ES-2
67181,2016,39.747991,-3.118078,45346,36.920000,cropland,ParcelasINES,ES,NaN,NaN,...,674.0,POINT (3196816.597 1947948.244),2,2,3190000.0,1951000.0,3200000.0,1941000.0,ES,ES-2
67216,2016,39.702947,-3.176326,45381,30.850000,cropland,ParcelasINES,ES,NaN,NaN,...,674.0,POINT (3191097.132 1943891.706),2,2,3190000.0,1951000.0,3200000.0,1941000.0,ES,ES-2
67217,2016,39.702913,-3.118095,45382,28.480000,cropland,ParcelasINES,ES,NaN,NaN,...,674.0,POINT (3196033.699 1943022.741),2,2,3190000.0,1951000.0,3200000.0,1941000.0,ES,ES-2
67484,2016,39.317458,-3.648182,45973,24.320000,woodland,ParcelasINES,ES,NaN,NaN,...,674.0,POINT (3144186.099 1908963.993),0,0,3140000.0,1911000.0,3150000.0,1901000.0,ES,ES-0
69983,2018,39.295756,-3.639110,130099,62.670000,grassland,ParcelasINES,ES,NaN,NaN,...,674.0,POINT (3144569.838 1906454.976),0,0,3140000.0,1911000.0,3150000.0,1901000.0,ES,ES-0
69984,2018,39.296060,-3.581129,130100,27.160000,grassland,ParcelasINES,ES,NaN,NaN,...,674.0,POINT (3149516.186 1905592.176),0,0,3140000.0,1911000.0,3150000.0,1901000.0,ES,ES-0
70015,2018,39.250705,-3.638701,130131,46.410000,grassland,ParcelasINES,ES,NaN,NaN,...,674.0,POINT (3143797.602 1901531.823),0,0,3140000.0,1911000.0,3150000.0,1901000.0,ES,ES-0
93590,2017,52.992590,11.831889,1003,4.454535,cropland,thuenen.bze.lw,DE,6.120159,1.419355,...,1055.0,POINT (4444000.834 3322000.745),1,1,4440000.0,3331000.0,4450000.0,3321000.0,DE,DE-1
93620,2017,53.065855,11.848541,944,4.885456,grassland,thuenen.bze.lw,DE,5.874878,1.807132,...,1055.0,POINT (4444909.330 3330179.680),1,1,4440000.0,3331000.0,4450000.0,3321000.0,DE,DE-1